# Generated by Django 4.1.7 on 2023-03-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tierthumbnailsize',
            old_name='thumbnail_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='tierthumbnailsize',
            old_name='user_tier',
            new_name='tier',
        ),
    ]
