# Generated by Django 4.1.7 on 2023-03-06 19:15

from django.db import migrations

def create_initial_tiers(apps, schema_editor):
    Tier = apps.get_model('users', 'Tier')
    TierThumbnailSize = apps.get_model('users', 'TierThumbnailSize')

    # Basic
    t = Tier.objects.create(name='Basic', original_image_access=False, expiring_link=False)
    t.save()
    t_size = TierThumbnailSize.objects.create(tier=t, size=200)
    t_size.save()

    # Premium
    t = Tier.objects.create(name='Premium', original_image_access=True, expiring_link=False)
    t.save()
    t_size = TierThumbnailSize.objects.create(tier=t, size=200)
    t_size.save()
    t_size = TierThumbnailSize.objects.create(tier=t, size=400)
    t_size.save()
    
    # Enterprise
    t = Tier.objects.create(name='Enterprise', original_image_access=True, expiring_link=True)
    t.save()
    t_size = TierThumbnailSize.objects.create(tier=t, size=200)
    t_size.save()
    t_size = TierThumbnailSize.objects.create(tier=t, size=400)
    t_size.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_thumbnail_size_tierthumbnailsize_size_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_tiers),
    ]
