services:
  db:
    image: postgres:14.7
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=images_app_db
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_PORT=5432
    expose:
      - 5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - LOCAL_SETTINGS=0
      - DBNAME=images_app_db
      - DBUSER=django
      - DBPASS=django
      - DBHOST=db
      - DBPORT=5432
    depends_on:
      - db
