# Generated by Django 4.1.7 on 2023-03-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_image_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='expiring',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imagelink',
            name='size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
